modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Mrthomas20121/TFC-Decoration/issues"

[[mods]]
modId="terrafirmadatagen"
version="1.1.6"
displayName="Terrafirmadatagen"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terrafirmadatagen"
authors="Mrthomas20121"
description='''
Add Java Datagen to be used with tfc mods
'''

[[dependencies.terrafirmadatagen]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"